package com.laboon;

import static org.junit.Assert.*;

import org.junit.Test;

public class RoomTest {

// This tests if the method hasItem() works.
// The method should return true if there is at least one item found.
	
	@Test
	public void testHasItem() {
		Room r = new Room(false,true,false,false,false);
		
		boolean result = r.hasItem();
		
		assertTrue(result);
	}

	
// This tests if the method hasSugar() works.
// The method should return false if there is no sugar found.	
	
	@Test
	public void testHasSugar() {
		Room r = new Room(false,true,false,false,false);
		
		boolean result = r.hasSugar();
		
		assertFalse(result);
	}
	
// This tests if the method hasCream() works.
// The method should return true if there is some cream found.	
	
	@Test
	public void testHasCream() {
		Room r = new Room(false,true,false,false,false);
		
		boolean result = r.hasCream();
		
		assertTrue(result);
	}

	
// This tests if the method hasCoffee() works.
// The method should return false if there is no coffee found.	
	
	@Test
	public void testHasCoffee() {
		Room r = new Room(false,true,false,false,false);
		
		boolean result = r.hasCoffee();
		
		assertFalse(result);
	}

	
// This tests if the method northExit() works.
// The method should return true if there is a door leading North in the current room.		
	
	@Test
	public void testNorthExit() {
		Room r = new Room(false,true,false,true,false);
		
		boolean result = r.northExit();
		
		assertTrue(result);
	}

	
// This tests if the method southExit() works.
// The method should return false if there is a door leading South in the current room.		
	
	@Test
	public void testSouthExit() {
		Room r = new Room(false,true,false,true,false);
		
		boolean result = r.southExit();
		
		assertFalse(result);
	}

// This eventually tests the private methods generateDescription(), getAdjective() and getNoun().
// The result from the method getDescription() will return the string to describe the room.
// The description should be generated by the methods generateDescription(), getAdjective() and getNoun().	
	
	@Test
	public void testGetDescription() {
		
		Room r = new Room(false,true,false,true,false);		
		String str = "\nYou see a Tight room.\n"
				+ "It has a Loose cake.\n"
				+ "A Smart door leads North.\n";
		
		String result = r.getDescription();
			
		assertEquals(result,str);
	}
}
